

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "bronze";


ALTER SCHEMA "bronze" OWNER TO "postgres";


CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "bronze"."insert_rightmove_properties"("_data" "jsonb") RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
    INSERT INTO bronze.rightmove_properties
    SELECT * FROM jsonb_to_recordset(_data) AS x(
        property_address TEXT,
        agent_address TEXT,
        agent_name TEXT,
        available_date TEXT,
        property_type TEXT,
        bedrooms TEXT,
        bathrooms TEXT,
        post_date TEXT,
        price TEXT,
        latitude TEXT,
        longitude TEXT,
        url TEXT
    );
END;
$$;


ALTER FUNCTION "bronze"."insert_rightmove_properties"("_data" "jsonb") OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "bronze"."rightmove_properties" (
    "id" integer NOT NULL,
    "agent_address" "text",
    "agent_name" "text",
    "available_date" "text",
    "bathrooms" integer,
    "bedrooms" integer,
    "latitude" double precision,
    "longitude" double precision,
    "post_date" "text",
    "price" "text",
    "property_address" "text",
    "property_type" "text",
    "url" "text"
);


ALTER TABLE "bronze"."rightmove_properties" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "bronze"."rightmove_properties_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "bronze"."rightmove_properties_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "bronze"."rightmove_properties_id_seq" OWNED BY "bronze"."rightmove_properties"."id";



CREATE TABLE IF NOT EXISTS "public"."rightmove_data" (
    "id" integer NOT NULL,
    "Property Address" "text",
    "Agent Address" "text",
    "Agent Name" "text",
    "Available Date" "text",
    "Property Type" "text",
    "Bedrooms" integer,
    "Bathrooms" integer,
    "Post Date" "text",
    "Price" "text",
    "Latitude" double precision,
    "Longitude" double precision,
    "URL" "text"
);


ALTER TABLE "public"."rightmove_data" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."rightmove_data_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "public"."rightmove_data_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."rightmove_data_id_seq" OWNED BY "public"."rightmove_data"."id";



CREATE TABLE IF NOT EXISTS "public"."try" (
    "id" integer NOT NULL,
    "year" "text" NOT NULL,
    "gdp" integer NOT NULL,
    "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE "public"."try" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."try_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "public"."try_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."try_id_seq" OWNED BY "public"."try"."id";



CREATE TABLE IF NOT EXISTS "public"."ukgdp" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "year" bigint,
    "gdp" bigint
);


ALTER TABLE "public"."ukgdp" OWNER TO "postgres";


ALTER TABLE "public"."ukgdp" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ukgdp_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "bronze"."rightmove_properties" ALTER COLUMN "id" SET DEFAULT "nextval"('"bronze"."rightmove_properties_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."rightmove_data" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."rightmove_data_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."try" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."try_id_seq"'::"regclass");



ALTER TABLE ONLY "bronze"."rightmove_properties"
    ADD CONSTRAINT "rightmove_properties_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rightmove_data"
    ADD CONSTRAINT "rightmove_data_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."try"
    ADD CONSTRAINT "try_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ukgdp"
    ADD CONSTRAINT "ukgdp_pkey" PRIMARY KEY ("id");





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";





GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";


























































































































































































GRANT ALL ON TABLE "bronze"."rightmove_properties" TO "anon";
GRANT ALL ON TABLE "bronze"."rightmove_properties" TO "authenticated";
GRANT ALL ON TABLE "bronze"."rightmove_properties" TO "service_role";


















GRANT ALL ON TABLE "public"."rightmove_data" TO "anon";
GRANT ALL ON TABLE "public"."rightmove_data" TO "authenticated";
GRANT ALL ON TABLE "public"."rightmove_data" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rightmove_data_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rightmove_data_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rightmove_data_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."try" TO "anon";
GRANT ALL ON TABLE "public"."try" TO "authenticated";
GRANT ALL ON TABLE "public"."try" TO "service_role";



GRANT ALL ON SEQUENCE "public"."try_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."try_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."try_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."ukgdp" TO "anon";
GRANT ALL ON TABLE "public"."ukgdp" TO "authenticated";
GRANT ALL ON TABLE "public"."ukgdp" TO "service_role";



GRANT ALL ON SEQUENCE "public"."ukgdp_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ukgdp_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ukgdp_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
