name: Deploy Migrations to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Pull Remote Migrations
        run: supabase db pull

      - name: Repair Migration History (If Needed)
        run: supabase migration repair || echo "Skipping migration repair"

      - name: Push Local Migrations to Remote Database
        run: supabase db push --include-all || echo "⚠️ Ensure remote and local migrations are in sync!"


      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db push
